<?php

namespace AppBundle\Repository;

/**
 * KilometrageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KilometrageRepository extends \Doctrine\ORM\EntityRepository
{
}
