<?php

namespace AppBundle\Repository;

/**
 * LieuReceptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LieuReceptionRepository extends \Doctrine\ORM\EntityRepository
{
}
