<?php

namespace AppBundle\Repository;

/**
 * NatureDeplacementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NatureDeplacementRepository extends \Doctrine\ORM\EntityRepository
{
}
