<?php

namespace AppBundle\Repository;

/**
 * PleinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PleinRepository extends \Doctrine\ORM\EntityRepository
{
}
