# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    encoders:
        AppBundle\Entity\Utilisateur:
            algorithm: bcrypt

    providers:
        our_db_provider:
            entity:
                 class: AppBundle:Utilisateur
                 property: emailUtilisateur

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            form_login:
                  login_path: login
                  check_path: login
            logout:
                  path: /logout
                  target: /
            provider: our_db_provider


    access_control:
            - { path: ^/admin, roles: ROLE_ADMIN }
            - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/, roles: [ROLE_ADMIN, ROLE_USER] }